### ISSUE TITLE
Syntax error?

### ISSUE THREAD

**Issue by AnderssonPeter** [coverallsapp/orb#7]
When i try to use this orb i get the following error:
```bash
#!powershell.exe -ExecutionPolicy Bypass
if false; then
  curl "https://coveralls.io/webhook?repo_token=COVERALLS_REPO_TOKEN" \
    -d "payload[build_num]=$CIRCLE_BUILD_NUM&payload[status]=done"
  exit 0
fi

sudo npm install -g coveralls

if [ ! $COVERALLS_REPO_TOKEN ]; then
  export COVERALLS_REPO_TOKEN=COVERALLS_REPO_TOKEN
fi

export COVERALLS_ENDPOINT=https://coveralls.io

export COVERALLS_FLAG_NAME=""

if false; then
  export COVERALLS_PARALLEL=true
fi

# check for lcov file presence:
if [ ! -r ./coverage/lcov.info ]; then
  echo "Please specify a valid 'path_to_lcov' parameter."
  exit 1
fi

cat ./coverage/lcov.info | coveralls --verbose
At line:1 char:3
+ if false; then
+   ~
Missing '(' after 'if' in if statement.
At line:9 char:3
+ if [ ! $COVERALLS_REPO_TOKEN ]; then
+   ~
Missing '(' after 'if' in if statement.
At line:9 char:5
+ if [ ! $COVERALLS_REPO_TOKEN ]; then
+     ~
Missing type name after '['.
At line:17 char:3
+ if false; then
+   ~
Missing '(' after 'if' in if statement.
At line:22 char:3
+ if [ ! -r ./coverage/lcov.info ]; then
+   ~
Missing '(' after 'if' in if statement.
At line:22 char:5
+ if [ ! -r ./coverage/lcov.info ]; then
+     ~
Missing type name after '['.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingOpenParenthesisInIfStatement
 

Exited with code exit status 1
CircleCI received exit code 1
```

i have defined a environment variable named COVERALLS_REPO_TOKEN.

My configuration:
```yaml
jobs:
  build:
    executor: win/default     
   
    steps:
      - checkout
      - run: dotnet build
      - run: dotnet test --no-build --logger "trx" --collect:"XPlat Code Coverage" --settings coverlet.runsettings
      - run:
          name: test results
          when: always
          command: |
              dotnet tool install -g trx2junit
              export PATH="$PATH;/root/.dotnet/tools"
              trx2junit CompressedStaticFiles.Tests/TestResults/*.trx
      - store_test_results:
          path: CompressedStaticFiles.Tests/TestResults
      - store_artifacts:
          path: CompressedStaticFiles.Tests/TestResults
          destination: TestResults
      - coveralls/upload
```
